<?php

/**
 * sfSympalContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sympal
 * @subpackage model
 * @author     lacyrhoades@gmail.com
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class sfSympalContent extends PluginsfSympalContent
{
}
