<?php

/**
 * BasesfSympalPage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * 
 * @method string       getTitle() Returns the current record's "title" value
 * @method sfSympalPage setTitle() Sets the current record's "title" value
 * 
 * @package    sympal
 * @subpackage model
 * @author     lacyrhoades@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfSympalPage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_sympal_page');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $sfsympalcontenttypetemplate0 = new sfSympalContentTypeTemplate(array(
             ));
        $this->actAs($sfsympalcontenttypetemplate0);
    }
}