#main:
#  title:       Waffles
#  description: Waffles
#  keywords:    Waffles
#  actions:
#    about:
#      title:       About Waffles
#      description: About Waffles
#      keywords:    About Waffles
