all:
  sympal_config:
    installed: true
    current_version: 1.0.0-ALPHA5
    sfSympalLb30ThemePlugin:
      installed: true
  content_types:
    sfSympalPage:
      content_templates:
        default_view:
          template: sympal_page/simple_view
        text_image_image:
          template: sympal_page/text_image_image
  theme:
    controller_options:
      default_theme: lb30
    themes:
      lb30: { layout: lb30_theme, stylesheets: [/sfSympalLb30ThemePlugin/css/lb30_theme.css, /sfSympalLb30ThemePlugin/css/960.css] }

dev:
  sympal_config:
    minifier:
      enabled: false
